import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'auth_service.dart';

enum AppLanguage { pl, es, de, nl, fr, en, pt }

class AppLanguageController extends ChangeNotifier {
  static const _key = 'app_language';
  AppLanguage _language = AppLanguage.pl;

  AppLanguage get language => _language;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(_key);
    if (saved == null) return;
    _language = AppLanguage.values.firstWhere(
      (item) => item.name == saved,
      orElse: () => AppLanguage.pl,
    );
    notifyListeners();
  }

  Future<void> setLanguage(AppLanguage language) async {
    _language = language;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, language.name);
    try {
      await AuthService.updatePreferredLanguage(language.name);
    } catch (_) {}
  }

  Future<void> loadForCurrentUser() async {
    try {
      final preferred = await AuthService.preferredLanguage();
      if (preferred == null) return;
      _language = AppLanguage.values.firstWhere(
        (item) => item.name == preferred,
        orElse: () => _language,
      );
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_key, _language.name);
      notifyListeners();
    } catch (_) {}
  }
}

class AppText {
  static const _values = {
    'pl': {
      'dashboard': 'Panel administracyjny', 'notifications': 'Powiadomienia', 'notifications_empty': 'Brak nowych powiadomień.',
      'work_area': 'Obszar pracy',
      'choose_module': 'Wybierz moduł, aby rozpocząć.',
      'horses': 'Konie', 'your_friends': 'Twoi przyjaciele',
      'horse_subtitle': 'Karty i stan zdrowia',
      'monitoring': 'Monitorowanie',
      'monitoring_subtitle': 'Dane w czasie rzeczywistym',
      'records': 'Rejestry',
      'records_subtitle': 'Historia i zdarzenia',
      'users': 'Użytkownicy', 'admin_role': 'Administrator',
      'users_subtitle': 'Zarządzaj dostępem',
      'veterinarian': 'Weterynarz',
      'veterinarian_subtitle': 'Dane i oceny',
      'settings': 'Ustawienia',
      'language': 'Język aplikacji',
      'save': 'Zapisz',
      'add': 'Dodaj',
      'logout': 'Wyloguj się',
      'in_development': 'Moduł w budowie',
      'horse_card': 'Karta konia',
      'veterinarian_card': 'Karta weterynarza',
      'owner_card': 'Karta właściciela', 'address': 'Adres', 'current_address': 'Aktualny adres',
      'national_id': 'PESEL / dowód osobisty', 'horse_id': 'Numer identyfikacyjny konia',
      'private_data_notice': 'Dane prywatne. Widoczne tylko po odblokowaniu.', 'show_data': 'Pokaż', 'hide_data': 'Ukryj',
      'pathologies': 'Patologie i choroby', 'horses_owned': 'Posiadane konie', 'license_number': 'Numer licencji weterynaryjnej', 'clinic_address': 'Adres kliniki lub gabinetu',
      'name': 'Imię i nazwisko',
      'email': 'Adres e-mail',
      'phone': 'Telefon',
      'clinic': 'Klinika',
      'breed': 'Rasa',
      'birth_date': 'Data urodzenia',
      'microchip': 'Numer mikrochipu',
      'notes': 'Obserwacje',
      'saved': 'Informacje zapisane',
      'connected_sensor': 'Połączony czujnik', 'live': 'Na żywo',
      'temperature': 'Temperatura', 'humidity': 'Wilgotność', 'ammonia': 'Amoniak',
      'air_quality': 'Jakość powietrza', 'sensor_notice': 'Dane demonstracyjne do czasu połączenia ESP32.',
      'add_record': 'Dodaj wpis', 'edit_record': 'Edytuj wpis', 'record_title': 'Tytuł wpisu', 'details': 'Szczegóły',
      'cancel': 'Anuluj', 'no_records': 'Brak zapisanych wpisów',
      'care_plan': 'Plan leczenia', 'add_medication': 'Dodaj lek', 'medication': 'Lek',
      'dose': 'Dawka', 'next_date': 'Następna data', 'no_medication': 'Brak zaplanowanych leków',
      'frequency': 'Częstotliwość', 'daily': 'Codziennie', 'weekly': 'Co tydzień', 'once': 'Jednorazowo',
      'owner': 'Właściciel', 'owner_subtitle': 'Dane kontaktowe', 'care_subtitle': 'Leki i terminy',
      'report': 'Raport PDF', 'report_subtitle': 'Eksport historii', 'generate_report': 'Generuj raport',
      'user_management': 'Zarządzanie użytkownikami', 'user_management_subtitle': 'Weryfikacja kont',
      'welcome': 'Witamy',
      'cctv': 'Kamery CCTV', 'cctv_subtitle': 'Monitoring obiektu',
      'chat': 'Czat', 'chat_subtitle': 'Rozmowa społeczności', 'private_message': 'Prywatnie', 'message_deleted': 'Wiadomość usunięta.',
      'welcome_message': 'Witamy w Equi_Harmony_Monitor', 'login': 'Zaloguj się',
      'create_account': 'Utwórz konto', 'forgot_password': 'Zapomniałem hasła',
      'admin_access': 'Dostęp administratora', 'show_password': 'Pokaż hasło', 'hide_password': 'Ukryj hasło',
      'password': 'Hasło', 'admin_only_access': 'Wejście wyłącznie dla administratorów',
      'admin_email': 'E-mail administratora', 'checking': 'Sprawdzanie...', 'enter_as_admin': 'Wejdź jako administrator',
      'invalid_admin_credentials': 'Nieprawidłowy e-mail, hasło lub rola administratora.',
      'select_roles': 'Wybierz jedną lub więcej ról:', 'role_admin': 'Administrator', 'role_owner': 'Właściciel koni', 'role_veterinarian': 'Weterynarz',
      'fill_required_fields': 'Uzupełnij imię, e-mail, hasło (6 znaków) i co najmniej jedną rolę.',
      'stable_name_optional': 'Nazwa stajni (opcjonalnie)', 'min_password_chars': 'Minimum 6 znaków',
      'account_exists_title': 'Konto już istnieje', 'account_exists_message': 'Konto z tym e-mailem już istnieje. Użyj innego e-maila lub zaloguj się.',
      'account_created_title': 'Konto utworzone', 'account_created_message': 'Twoje konto administratora zostało utworzone poprawnie.',
      'request_sent_title': 'Zgłoszenie wysłane', 'request_sent_message': 'Konto zostało poprawnie zapisane i oczekuje na zatwierdzenie.',
      'register_pending_notice': 'Podaj tylko imię, e-mail i hasło. Rolę i zatwierdzenie ustali administrator/asystent.',
      'select_roles_required': 'Wybierz co najmniej jedną rolę przed zatwierdzeniem.',
      'account_error_title': 'Nie udało się utworzyć konta', 'account_error_message_prefix': 'Wystąpił błąd podczas zapisywania:',
      'accept': 'Akceptuj', 'saving': 'Zapisywanie...', 'submit_request': 'Wyślij zgłoszenie',
      'reset_password': 'Zresetuj hasło', 'new_password': 'Nowe hasło', 'password_updated': 'Hasło zaktualizowane. Możesz się teraz zalogować.',
      'email_not_found': 'Nie znaleziono e-maila lub hasło jest za krótkie.',
      'add_camera': 'Dodaj kamerę', 'add_camera_title': 'Dodaj kamerę CCTV', 'camera_name': 'Nazwa kamery', 'camera_url': 'URL/IP lub RTSP',
      'camera_open_error': 'Nie udało się otworzyć kamery. Sprawdź adres URL, sieć Wi-Fi i protokół.',
      'no_cameras': 'Dodaj kamerę Wi-Fi przez URL/IP lub RTSP.',
      'chat_access_required': 'Administrator musi przyznać ci dostęp do czatu.', 'chat_community': 'Czat społeczności',
      'play_voice_message': 'Odtwórz wiadomość głosową', 'send_message_error': 'Nie udało się wysłać wiadomości:',
      'video_label': 'Wideo', 'photo_label': 'Zdjęcie',
      'photo_or_video': 'Zdjęcie lub wideo', 'stop_recording': 'Zatrzymaj nagrywanie', 'record_voice': 'Nagraj głos',
      'write_message_hint': 'Napisz wiadomość lub emoji', 'send': 'Wyślij',
      'validate_users': 'Weryfikacja użytkowników', 'add_administrator': 'Dodaj administratora', 'no_users': 'Brak zarejestrowanych użytkowników.',
      'chat_room_access': 'Dostęp do pokoju czatu', 'reject': 'Odrzuć', 'approve': 'Zatwierdź', 'delete_account': 'Usuń konto',
      'delete_account_confirm_prefix': 'Czy chcesz usunąć konto użytkownika', 'delete_account_confirm_suffix': '? Tej czynności nie można cofnąć.',
      'account_deleted': 'Konto usunięte.', 'account_delete_error': 'Nie można usunąć tego konta.',
      'stable_label': 'Stajnia', 'status_label': 'Status', 'roles_label': 'Role',
      'administrator_added': 'Administrator dodany.', 'administrator_add_error': 'Nie udało się dodać. E-mail może już istnieć.',
      'delete_local_account': 'Usuń moje lokalne konto', 'delete': 'Usuń', 'delete_post': 'Usuń publikację', 'delete_post_confirm': 'Czy na pewno usunąć tę publikację?', 'reaction': 'Reakcja',
      'delete_account_warning': 'Bieżące lokalne konto zostanie usunięte i będzie można utworzyć inne. Tej czynności nie można cofnąć.',
      'password_privacy_note': 'Ze względów bezpieczeństwa hasło nie jest zapisywane automatycznie. E-mail może być zapamiętany.',
      'support_us': 'Wesprzyj nas', 'support_title': 'Wesprzyj rozwój',
      'support_message': 'Pamiętaj, że utrzymanie aplikacji wiąże się z kosztami. Jeśli chcesz, możesz wesprzeć nas dowolną kwotą, aby pomóc w rozwoju i ulepszaniu aplikacji. Bardzo dziękujemy!',
      'blick_number': 'Numer Blik', 'close': 'Zamknij', 'number_copied': 'Numer skopiowany',
      'pending_users_notice': 'Masz oczekujące konta do zatwierdzenia',
      'no_account_found': 'Nie ma konta z tym adresem e-mail.', 'password_mismatch': 'Hasło się nie zgadza.',
      'account_pending_approval': 'Konto oczekuje na zatwierdzenie przez administratora.', 'login_failed_generic': 'Nie udało się zalogować.',
      'reset_link_sent': 'Wysłaliśmy link do zresetowania hasła na twój e-mail.',
      'reset_link_instructions': 'Wpisz swój e-mail, a wyślemy ci link do ustawienia nowego hasła.',
      'feed': 'Tablica', 'feed_subtitle': 'Zdjęcia i chwile ze stajni', 'new_post': 'Nowy post', 'post_caption_hint': 'Napisz coś...',
      'add_photo': 'Dodaj zdjęcie', 'add_photo_video': 'Dodaj zdjęcie lub wideo', 'play_video': 'Odtwórz wideo', 'publish': 'Opublikuj', 'no_posts': 'Brak publikacji. Bądź pierwszy!', 'comment': 'Skomentuj',
      'post_error': 'Nie udało się opublikować:',
      'stable_facebook': 'Facebook stajni',
      'transfer_primary_title': 'Zmienić głównego administratora', 'transfer_primary_action': 'Ustaw jako głównego administratora',
      'transfer_primary_confirm_prefix': 'Czy chcesz uczynić', 'transfer_primary_confirm_suffix': 'głównym administratorem? Ty przestaniesz nim być.',
      'transfer_primary_success': 'Rola głównego administratora została przekazana.', 'transfer_primary_error': 'Nie udało się przekazać roli.',
      'owner_panel_title': 'Panel konserwacji',
    },
    'es': {
      'dashboard': 'Panel de administración', 'notifications': 'Notificaciones', 'notifications_empty': 'No hay notificaciones nuevas.', 'work_area': 'Área de trabajo',
      'choose_module': 'Selecciona un módulo para comenzar.', 'horses': 'Caballos', 'your_friends': 'Tus amigos',
      'horse_subtitle': 'Fichas y estado de salud', 'monitoring': 'Monitoreo',
      'monitoring_subtitle': 'Datos en tiempo real', 'records': 'Registros',
      'records_subtitle': 'Historial y eventos', 'users': 'Usuarios', 'admin_role': 'Administrador',
      'users_subtitle': 'Administrar accesos', 'veterinarian': 'Veterinario',
      'veterinarian_subtitle': 'Datos y evaluaciones', 'settings': 'Configuración',
      'language': 'Idioma de la aplicación', 'save': 'Guardar', 'add': 'Agregar',
      'logout': 'Cerrar sesión', 'in_development': 'Módulo en construcción',
      'horse_card': 'Ficha del caballo', 'veterinarian_card': 'Ficha del veterinario',
      'owner_card': 'Ficha del propietario', 'address': 'Dirección', 'current_address': 'Dirección actual',
      'national_id': 'PESEL / documento de identidad', 'horse_id': 'Número de identificación del caballo',
      'private_data_notice': 'Dato privado. Solo visible al desbloquearlo.', 'show_data': 'Mostrar', 'hide_data': 'Ocultar',
      'pathologies': 'Patologías y enfermedades', 'horses_owned': 'Caballos que posee', 'license_number': 'Número de licencia veterinaria', 'clinic_address': 'Dirección de clínica o consulta',
      'name': 'Nombre completo', 'email': 'Correo electrónico', 'phone': 'Teléfono',
      'clinic': 'Clínica', 'breed': 'Raza', 'birth_date': 'Fecha de nacimiento', 'birth_date_required': 'Toca para seleccionar tu fecha de nacimiento', 'age_restriction': 'Solo pueden registrarse personas de 18 años o más.',
      'microchip': 'Número de microchip', 'notes': 'Observaciones', 'saved': 'Información guardada',
      'connected_sensor': 'Sensor conectado', 'live': 'En vivo', 'temperature': 'Temperatura',
      'humidity': 'Humedad', 'ammonia': 'Amoníaco', 'air_quality': 'Calidad del aire',
      'sensor_notice': 'Datos de demostración hasta conectar el ESP32.', 'add_record': 'Añadir registro', 'edit_record': 'Editar registro',
      'record_title': 'Título del registro', 'details': 'Detalles', 'cancel': 'Cancelar',
      'no_records': 'No hay registros guardados',
      'care_plan': 'Plan de tratamiento', 'add_medication': 'Añadir medicación', 'medication': 'Medicamento',
      'dose': 'Dosis', 'next_date': 'Próxima fecha', 'no_medication': 'No hay medicación programada',
      'frequency': 'Frecuencia', 'daily': 'Diaria', 'weekly': 'Semanal', 'once': 'Una vez',
      'owner': 'Propietario', 'owner_subtitle': 'Datos de contacto', 'care_subtitle': 'Medicamentos y fechas',
      'report': 'Informe PDF', 'report_subtitle': 'Exportar historial', 'generate_report': 'Generar informe',
      'user_management': 'Gestión de usuarios', 'user_management_subtitle': 'Validar cuentas',
      'welcome': 'Bienvenido',
      'cctv': 'Cámaras CCTV', 'cctv_subtitle': 'Seguridad del establo',
      'chat': 'Chat', 'chat_subtitle': 'Sala de la comunidad', 'private_message': 'Privado', 'message_deleted': 'Mensaje eliminado.',
      'welcome_message': 'Bienvenido a Equi_Harmony_Monitor', 'login': 'Iniciar sesión',
      'create_account': 'Crear cuenta', 'forgot_password': 'Olvidé mi contraseña',
      'admin_access': 'Acceso administrador', 'show_password': 'Mostrar contraseña', 'hide_password': 'Ocultar contraseña',
      'password': 'Contraseña', 'admin_only_access': 'Entrada exclusiva para administradores',
      'admin_email': 'Correo administrador', 'checking': 'Comprobando...', 'enter_as_admin': 'Entrar como administrador',
      'invalid_admin_credentials': 'Correo, contraseña o rol administrador incorrecto.',
      'select_roles': 'Selecciona uno o varios roles:', 'role_admin': 'Administrador', 'role_owner': 'Dueño de caballos', 'role_veterinarian': 'Veterinario',
      'fill_required_fields': 'Completa nombre, correo, contraseña de 6 caracteres y al menos un rol.',
      'stable_name_optional': 'Nombre del establo (opcional)', 'min_password_chars': 'Mínimo 6 caracteres',
      'account_exists_title': 'Cuenta existente', 'account_exists_message': 'Ya existe una cuenta con ese correo. Usa otro correo o inicia sesión.',
      'account_created_title': 'Cuenta creada', 'account_created_message': 'Tu cuenta de administrador fue creada correctamente.',
      'request_sent_title': 'Solicitud enviada', 'request_sent_message': 'La cuenta se guardó correctamente y está pendiente de aprobación.',
      'register_pending_notice': 'Solo indica tu nombre, correo y contraseña. El rol y la aprobación los define el administrador/asistente.',
      'select_roles_required': 'Selecciona al menos un rol antes de aprobar.',
      'account_error_title': 'No se pudo crear la cuenta', 'account_error_message_prefix': 'Ocurrió un error al guardar:',
      'accept': 'Aceptar', 'saving': 'Guardando...', 'submit_request': 'Enviar solicitud',
      'reset_password': 'Restablecer contraseña', 'new_password': 'Nueva contraseña', 'password_updated': 'Contraseña actualizada. Ya puedes iniciar sesión.',
      'email_not_found': 'Correo no encontrado o contraseña demasiado corta.',
      'add_camera': 'Agregar cámara', 'add_camera_title': 'Agregar cámara CCTV', 'camera_name': 'Nombre de la cámara', 'camera_url': 'URL/IP o RTSP',
      'camera_open_error': 'No se pudo abrir la cámara. Comprueba la URL, la red Wi-Fi y el protocolo.',
      'no_cameras': 'Agrega una cámara Wi-Fi por URL/IP o RTSP.',
      'chat_access_required': 'El administrador debe darte acceso al chat.', 'chat_community': 'Chat de la comunidad',
      'play_voice_message': 'Reproducir mensaje de voz', 'send_message_error': 'No se pudo enviar el mensaje:',
      'video_label': 'Video', 'photo_label': 'Foto',
      'photo_or_video': 'Foto o video', 'stop_recording': 'Detener grabación', 'record_voice': 'Grabar voz',
      'write_message_hint': 'Escribe un mensaje o emoji', 'send': 'Enviar',
      'validate_users': 'Validación de usuarios', 'add_administrator': 'Agregar administrador', 'no_users': 'No hay usuarios registrados.',
      'chat_room_access': 'Acceso a la sala de chat', 'reject': 'Rechazar', 'approve': 'Aprobar', 'delete_account': 'Eliminar cuenta',
      'delete_account_confirm_prefix': '¿Quieres eliminar la cuenta de', 'delete_account_confirm_suffix': '? Esta acción no se puede deshacer.',
      'account_deleted': 'Cuenta eliminada.', 'account_delete_error': 'No se puede eliminar esta cuenta.',
      'stable_label': 'Establo', 'status_label': 'Estado', 'roles_label': 'Roles',
      'administrator_added': 'Administrador agregado.', 'administrator_add_error': 'No se pudo agregar. El correo puede existir.',
      'delete_local_account': 'Eliminar mi cuenta local', 'delete': 'Eliminar', 'delete_post': 'Eliminar publicación', 'delete_post_confirm': '¿Quieres eliminar esta publicación?', 'reaction': 'Reacción',
      'delete_account_warning': 'Se borrará la cuenta local actual y podrás crear otra. Esta acción no se puede deshacer.',
      'password_privacy_note': 'Por seguridad, la contraseña no se guarda automáticamente. El correo sí puede recordarse.',
      'support_us': 'Apóyanos', 'support_title': 'Apoya el desarrollo',
      'support_message': 'Por favor recuerda que el mantenimiento de la app tiene un costo. Si lo deseas, puedes apoyarnos con la donación que gustes para ayudar al desarrollo y mejora de la aplicación. ¡Te lo agradecemos mucho!',
      'blick_number': 'Número Blick', 'close': 'Cerrar', 'number_copied': 'Número copiado',
      'pending_users_notice': 'Tienes cuentas pendientes de aprobar',
      'no_account_found': 'No existe una cuenta con ese correo.', 'password_mismatch': 'La contraseña no coincide.',
      'account_pending_approval': 'La cuenta está pendiente de aprobación por un administrador.', 'login_failed_generic': 'No se pudo iniciar sesión.',
      'reset_link_sent': 'Te enviamos un enlace para restablecer tu contraseña a tu correo.',
      'reset_link_instructions': 'Escribe tu correo y te enviaremos un enlace para crear una nueva contraseña.',
      'feed': 'Muro', 'feed_subtitle': 'Fotos y momentos del establo', 'new_post': 'Nueva publicación', 'post_caption_hint': 'Escribe algo...',
      'add_photo': 'Agregar foto', 'add_photo_video': 'Agregar foto o video', 'play_video': 'Reproducir video', 'publish': 'Publicar', 'no_posts': 'Aún no hay publicaciones. ¡Sé el primero!', 'comment': 'Comentar',
      'post_error': 'No se pudo publicar:',
      'stable_facebook': 'Facebook del establo',
      'transfer_primary_title': 'Cambiar administrador principal', 'transfer_primary_action': 'Hacer administrador principal',
      'transfer_primary_confirm_prefix': '¿Quieres hacer a', 'transfer_primary_confirm_suffix': 'el administrador principal? Tú dejarás de serlo.',
      'transfer_primary_success': 'El rol de administrador principal fue transferido.', 'transfer_primary_error': 'No se pudo transferir el rol.',
      'owner_panel_title': 'Panel de mantenimiento',
    },
    'de': {
      'dashboard': 'Administrationsbereich', 'notifications': 'Benachrichtigungen', 'notifications_empty': 'Keine neuen Benachrichtigungen.', 'work_area': 'Arbeitsbereich',
      'choose_module': 'Wählen Sie ein Modul aus.', 'horses': 'Pferde', 'your_friends': 'Deine Freunde',
      'horse_subtitle': 'Profile und Gesundheitsstatus', 'monitoring': 'Überwachung',
      'monitoring_subtitle': 'Echtzeitdaten', 'records': 'Aufzeichnungen',
      'records_subtitle': 'Verlauf und Ereignisse', 'users': 'Benutzer', 'admin_role': 'Administrator',
      'users_subtitle': 'Zugänge verwalten', 'veterinarian': 'Tierarzt',
      'veterinarian_subtitle': 'Daten und Bewertungen', 'settings': 'Einstellungen',
      'language': 'App-Sprache', 'save': 'Speichern', 'add': 'Hinzufügen',
      'logout': 'Abmelden', 'in_development': 'Modul in Entwicklung',
      'horse_card': 'Pferdeprofil', 'veterinarian_card': 'Tierarztprofil',
      'owner_card': 'Besitzerprofil', 'address': 'Adresse', 'current_address': 'Aktuelle Adresse',
      'national_id': 'PESEL / Ausweis', 'horse_id': 'Identifikationsnummer des Pferdes',
      'private_data_notice': 'Private Daten. Nur nach dem Entsperren sichtbar.', 'show_data': 'Anzeigen', 'hide_data': 'Ausblenden',
      'pathologies': 'Krankheiten und Pathologien', 'horses_owned': 'Eigene Pferde', 'license_number': 'Tierärztliche Lizenznummer', 'clinic_address': 'Adresse der Klinik oder Praxis',
      'name': 'Vollständiger Name', 'email': 'E-Mail', 'phone': 'Telefon',
      'clinic': 'Klinik', 'breed': 'Rasse', 'birth_date': 'Geburtsdatum', 'birth_date_required': 'Tippen, um das Geburtsdatum auszuwählen', 'age_restriction': 'Registrierung ist erst ab 18 Jahren möglich.',
      'microchip': 'Mikrochipnummer', 'notes': 'Notizen', 'saved': 'Information gespeichert',
      'connected_sensor': 'Sensor verbunden', 'live': 'Live', 'temperature': 'Temperatur',
      'humidity': 'Luftfeuchtigkeit', 'ammonia': 'Ammoniak', 'air_quality': 'Luftqualität',
      'sensor_notice': 'Demodaten bis zur Verbindung mit dem ESP32.', 'add_record': 'Eintrag hinzufügen',
      'record_title': 'Titel', 'details': 'Details', 'cancel': 'Abbrechen', 'no_records': 'Keine Einträge gespeichert',
      'care_plan': 'Behandlungsplan', 'add_medication': 'Medikament hinzufügen', 'medication': 'Medikament',
      'dose': 'Dosis', 'next_date': 'Nächstes Datum', 'no_medication': 'Keine Medikamente geplant',
      'frequency': 'Häufigkeit', 'daily': 'Täglich', 'weekly': 'Wöchentlich', 'once': 'Einmalig',
      'owner': 'Besitzer', 'owner_subtitle': 'Kontaktdaten', 'care_subtitle': 'Medikamente und Termine',
      'report': 'PDF-Bericht', 'report_subtitle': 'Verlauf exportieren', 'generate_report': 'Bericht erstellen',
      'user_management': 'Benutzerverwaltung', 'user_management_subtitle': 'Konten prüfen',
      'welcome': 'Willkommen',
      'cctv': 'CCTV-Kameras', 'cctv_subtitle': 'Objektüberwachung',
      'chat': 'Chat', 'chat_subtitle': 'Gemeinschaftsraum', 'private_message': 'Privat', 'message_deleted': 'Nachricht gelöscht.',
      'welcome_message': 'Willkommen bei Equi_Harmony_Monitor', 'login': 'Anmelden',
      'create_account': 'Konto erstellen', 'forgot_password': 'Passwort vergessen',
      'admin_access': 'Administratorzugang', 'show_password': 'Passwort anzeigen', 'hide_password': 'Passwort verbergen',
      'password': 'Passwort', 'admin_only_access': 'Zugang nur für Administratoren',
      'admin_email': 'Administrator-E-Mail', 'checking': 'Wird geprüft...', 'enter_as_admin': 'Als Administrator anmelden',
      'invalid_admin_credentials': 'Falsche E-Mail, falsches Passwort oder keine Administratorrolle.',
      'select_roles': 'Wählen Sie eine oder mehrere Rollen:', 'role_admin': 'Administrator', 'role_owner': 'Pferdebesitzer', 'role_veterinarian': 'Tierarzt',
      'fill_required_fields': 'Geben Sie Name, E-Mail, ein Passwort mit 6 Zeichen und mindestens eine Rolle ein.',
      'stable_name_optional': 'Stallname (optional)', 'min_password_chars': 'Mindestens 6 Zeichen',
      'account_exists_title': 'Konto existiert bereits', 'account_exists_message': 'Es existiert bereits ein Konto mit dieser E-Mail. Verwenden Sie eine andere E-Mail oder melden Sie sich an.',
      'account_created_title': 'Konto erstellt', 'account_created_message': 'Ihr Administratorkonto wurde erfolgreich erstellt.',
      'request_sent_title': 'Anfrage gesendet', 'request_sent_message': 'Das Konto wurde erfolgreich gespeichert und wartet auf Genehmigung.',
      'register_pending_notice': 'Geben Sie nur Namen, E-Mail und Passwort an. Rolle und Freigabe legt der Administrator/Assistent fest.',
      'select_roles_required': 'Wählen Sie mindestens eine Rolle aus, bevor Sie genehmigen.',
      'account_error_title': 'Konto konnte nicht erstellt werden', 'account_error_message_prefix': 'Beim Speichern ist ein Fehler aufgetreten:',
      'accept': 'Akzeptieren', 'saving': 'Wird gespeichert...', 'submit_request': 'Anfrage senden',
      'reset_password': 'Passwort zurücksetzen', 'new_password': 'Neues Passwort', 'password_updated': 'Passwort aktualisiert. Sie können sich jetzt anmelden.',
      'email_not_found': 'E-Mail nicht gefunden oder Passwort zu kurz.',
      'add_camera': 'Kamera hinzufügen', 'add_camera_title': 'CCTV-Kamera hinzufügen', 'camera_name': 'Kameraname', 'camera_url': 'URL/IP oder RTSP',
      'camera_open_error': 'Kamera konnte nicht geöffnet werden. Überprüfen Sie URL, WLAN und Protokoll.',
      'no_cameras': 'Fügen Sie eine WLAN-Kamera über URL/IP oder RTSP hinzu.',
      'chat_access_required': 'Der Administrator muss Ihnen Zugriff auf den Chat gewähren.', 'chat_community': 'Community-Chat',
      'play_voice_message': 'Sprachnachricht abspielen', 'send_message_error': 'Nachricht konnte nicht gesendet werden:',
      'video_label': 'Video', 'photo_label': 'Foto',
      'photo_or_video': 'Foto oder Video', 'stop_recording': 'Aufnahme stoppen', 'record_voice': 'Stimme aufnehmen',
      'write_message_hint': 'Nachricht oder Emoji schreiben', 'send': 'Senden',
      'validate_users': 'Benutzervalidierung', 'add_administrator': 'Administrator hinzufügen', 'no_users': 'Keine registrierten Benutzer.',
      'chat_room_access': 'Zugang zum Chatraum', 'reject': 'Ablehnen', 'approve': 'Genehmigen', 'delete_account': 'Konto löschen',
      'delete_account_confirm_prefix': 'Möchten Sie das Konto von', 'delete_account_confirm_suffix': '? Diese Aktion kann nicht rückgängig gemacht werden.',
      'account_deleted': 'Konto gelöscht.', 'account_delete_error': 'Dieses Konto kann nicht gelöscht werden.',
      'stable_label': 'Stall', 'status_label': 'Status', 'roles_label': 'Rollen',
      'administrator_added': 'Administrator hinzugefügt.', 'administrator_add_error': 'Hinzufügen fehlgeschlagen. Die E-Mail existiert möglicherweise bereits.',
      'delete_local_account': 'Mein lokales Konto löschen', 'delete': 'Löschen', 'delete_post': 'Beitrag löschen', 'delete_post_confirm': 'Diesen Beitrag löschen?', 'reaction': 'Reaktion',
      'delete_account_warning': 'Das aktuelle lokale Konto wird gelöscht und Sie können ein neues erstellen. Diese Aktion kann nicht rückgängig gemacht werden.',
      'password_privacy_note': 'Aus Sicherheitsgründen wird das Passwort nicht automatisch gespeichert. Die E-Mail kann jedoch gespeichert werden.',
      'support_us': 'Unterstütze uns', 'support_title': 'Unterstütze die Entwicklung',
      'support_message': 'Bitte denken Sie daran, dass die Wartung der App Kosten verursacht. Wenn Sie möchten, können Sie uns mit einer beliebigen Spende unterstützen, um die Entwicklung und Verbesserung der App zu fördern. Vielen Dank!',
      'blick_number': 'Blick-Nummer', 'close': 'Schließen', 'number_copied': 'Nummer kopiert',
      'pending_users_notice': 'Es gibt Konten, die auf Genehmigung warten',
      'no_account_found': 'Es gibt kein Konto mit dieser E-Mail.', 'password_mismatch': 'Das Passwort stimmt nicht überein.',
      'account_pending_approval': 'Das Konto wartet auf die Genehmigung durch einen Administrator.', 'login_failed_generic': 'Anmeldung fehlgeschlagen.',
      'reset_link_sent': 'Wir haben einen Link zum Zurücksetzen des Passworts an Ihre E-Mail gesendet.',
      'reset_link_instructions': 'Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Link, um ein neues Passwort festzulegen.',
      'feed': 'Pinnwand', 'feed_subtitle': 'Fotos und Momente aus dem Stall', 'new_post': 'Neuer Beitrag', 'post_caption_hint': 'Schreib etwas...',
      'add_photo': 'Foto hinzufügen', 'add_photo_video': 'Foto oder Video hinzufügen', 'play_video': 'Video abspielen', 'publish': 'Veröffentlichen', 'no_posts': 'Noch keine Beiträge. Sei der Erste!', 'comment': 'Kommentieren',
      'post_error': 'Veröffentlichung fehlgeschlagen:',
      'stable_facebook': 'Facebook des Stalls',
      'transfer_primary_title': 'Hauptadministrator ändern', 'transfer_primary_action': 'Zum Hauptadministrator machen',
      'transfer_primary_confirm_prefix': 'Möchten Sie', 'transfer_primary_confirm_suffix': 'zum Hauptadministrator machen? Sie werden diese Rolle verlieren.',
      'transfer_primary_success': 'Die Rolle des Hauptadministrators wurde übertragen.', 'transfer_primary_error': 'Die Rolle konnte nicht übertragen werden.',
      'owner_panel_title': 'Wartungspanel',
    },
    'nl': {
      'dashboard': 'Beheerpaneel', 'notifications': 'Meldingen', 'notifications_empty': 'Geen nieuwe meldingen.', 'work_area': 'Werkruimte',
      'choose_module': 'Kies een module om te beginnen.', 'horses': 'Paarden', 'your_friends': 'Jouw vrienden',
      'horse_subtitle': 'Profielen en gezondheid', 'monitoring': 'Monitoring',
      'monitoring_subtitle': 'Realtime gegevens', 'records': 'Registraties',
      'records_subtitle': 'Geschiedenis en gebeurtenissen', 'users': 'Gebruikers', 'admin_role': 'Beheerder',
      'users_subtitle': 'Toegang beheren', 'veterinarian': 'Dierenarts',
      'veterinarian_subtitle': 'Gegevens en beoordelingen', 'settings': 'Instellingen',
      'language': 'App-taal', 'save': 'Opslaan', 'add': 'Toevoegen',
      'logout': 'Uitloggen', 'in_development': 'Module in ontwikkeling',
      'horse_card': 'Paardenprofiel', 'veterinarian_card': 'Dierenartsprofiel',
      'owner_card': 'Eigenaarprofiel', 'address': 'Adres', 'current_address': 'Huidig adres',
      'national_id': 'PESEL / identiteitsbewijs', 'horse_id': 'Identificatienummer paard',
      'private_data_notice': 'Privégegevens. Alleen zichtbaar na ontgrendeling.', 'show_data': 'Tonen', 'hide_data': 'Verbergen',
      'pathologies': 'Aandoeningen en ziekten', 'horses_owned': 'Eigen paarden', 'license_number': 'Dierenartslicentienummer', 'clinic_address': 'Adres kliniek of praktijk',
      'name': 'Volledige naam', 'email': 'E-mail', 'phone': 'Telefoon',
      'clinic': 'Kliniek', 'breed': 'Ras', 'birth_date': 'Geboortedatum', 'birth_date_required': 'Tik om je geboortedatum te kiezen', 'age_restriction': 'Registratie is alleen toegestaan vanaf 18 jaar.',
      'microchip': 'Microchipnummer', 'notes': 'Opmerkingen', 'saved': 'Informatie opgeslagen',
      'connected_sensor': 'Verbonden sensor', 'live': 'Live', 'temperature': 'Temperatuur',
      'humidity': 'Vochtigheid', 'ammonia': 'Ammoniak', 'air_quality': 'Luchtkwaliteit',
      'sensor_notice': 'Demogegevens totdat de ESP32 is verbonden.', 'add_record': 'Registratie toevoegen',
      'record_title': 'Titel', 'details': 'Details', 'cancel': 'Annuleren', 'no_records': 'Geen registraties opgeslagen',
      'care_plan': 'Behandelplan', 'add_medication': 'Medicatie toevoegen', 'medication': 'Medicijn',
      'dose': 'Dosis', 'next_date': 'Volgende datum', 'no_medication': 'Geen medicatie gepland',
      'frequency': 'Frequentie', 'daily': 'Dagelijks', 'weekly': 'Wekelijks', 'once': 'Eenmalig',
      'owner': 'Eigenaar', 'owner_subtitle': 'Contactgegevens', 'care_subtitle': 'Medicatie en datums',
      'report': 'PDF-rapport', 'report_subtitle': 'Geschiedenis exporteren', 'generate_report': 'Rapport maken',
      'user_management': 'Gebruikersbeheer', 'user_management_subtitle': 'Accounts valideren',
      'welcome': 'Welkom',
      'cctv': 'CCTV-camera’s', 'cctv_subtitle': 'Bewaking van de stal',
      'chat': 'Chat', 'chat_subtitle': 'Gemeenschapsruimte', 'private_message': 'Privé', 'message_deleted': 'Bericht verwijderd.',
      'welcome_message': 'Welkom bij Equi_Harmony_Monitor', 'login': 'Inloggen',
      'create_account': 'Account aanmaken', 'forgot_password': 'Wachtwoord vergeten',
      'admin_access': 'Beheerderstoegang', 'show_password': 'Wachtwoord tonen', 'hide_password': 'Wachtwoord verbergen',
      'password': 'Wachtwoord', 'admin_only_access': 'Alleen toegang voor beheerders',
      'admin_email': 'Beheerder e-mail', 'checking': 'Controleren...', 'enter_as_admin': 'Inloggen als beheerder',
      'invalid_admin_credentials': 'Onjuiste e-mail, wachtwoord of beheerdersrol.',
      'select_roles': 'Selecteer een of meer rollen:', 'role_admin': 'Beheerder', 'role_owner': 'Paardeneigenaar', 'role_veterinarian': 'Dierenarts',
      'fill_required_fields': 'Vul naam, e-mail, wachtwoord van 6 tekens en minstens één rol in.',
      'stable_name_optional': 'Naam van de stal (optioneel)', 'min_password_chars': 'Minimaal 6 tekens',
      'account_exists_title': 'Account bestaat al', 'account_exists_message': 'Er bestaat al een account met dit e-mailadres. Gebruik een ander e-mailadres of log in.',
      'account_created_title': 'Account aangemaakt', 'account_created_message': 'Uw beheerdersaccount is succesvol aangemaakt.',
      'request_sent_title': 'Aanvraag verzonden', 'request_sent_message': 'Het account is succesvol opgeslagen en wacht op goedkeuring.',
      'register_pending_notice': 'Vul alleen naam, e-mail en wachtwoord in. De rol en goedkeuring worden bepaald door de beheerder/assistent.',
      'select_roles_required': 'Selecteer minstens één rol voordat u goedkeurt.',
      'account_error_title': 'Account kon niet worden aangemaakt', 'account_error_message_prefix': 'Er is een fout opgetreden bij het opslaan:',
      'accept': 'Accepteren', 'saving': 'Opslaan...', 'submit_request': 'Aanvraag versturen',
      'reset_password': 'Wachtwoord resetten', 'new_password': 'Nieuw wachtwoord', 'password_updated': 'Wachtwoord bijgewerkt. U kunt nu inloggen.',
      'email_not_found': 'E-mail niet gevonden of wachtwoord te kort.',
      'add_camera': 'Camera toevoegen', 'add_camera_title': 'CCTV-camera toevoegen', 'camera_name': 'Cameranaam', 'camera_url': 'URL/IP of RTSP',
      'camera_open_error': 'Camera kon niet worden geopend. Controleer de URL, het wifi-netwerk en het protocol.',
      'no_cameras': 'Voeg een wifi-camera toe via URL/IP of RTSP.',
      'chat_access_required': 'De beheerder moet u toegang tot de chat geven.', 'chat_community': 'Community chat',
      'play_voice_message': 'Spraakbericht afspelen', 'send_message_error': 'Bericht kon niet worden verzonden:',
      'video_label': 'Video', 'photo_label': 'Foto',
      'photo_or_video': 'Foto of video', 'stop_recording': 'Opname stoppen', 'record_voice': 'Stem opnemen',
      'write_message_hint': 'Schrijf een bericht of emoji', 'send': 'Verzenden',
      'validate_users': 'Gebruikersvalidatie', 'add_administrator': 'Beheerder toevoegen', 'no_users': 'Geen geregistreerde gebruikers.',
      'chat_room_access': 'Toegang tot de chatroom', 'reject': 'Afwijzen', 'approve': 'Goedkeuren', 'delete_account': 'Account verwijderen',
      'delete_account_confirm_prefix': 'Wilt u het account van', 'delete_account_confirm_suffix': '? Deze actie kan niet ongedaan worden gemaakt.',
      'account_deleted': 'Account verwijderd.', 'account_delete_error': 'Dit account kan niet worden verwijderd.',
      'stable_label': 'Stal', 'status_label': 'Status', 'roles_label': 'Rollen',
      'administrator_added': 'Beheerder toegevoegd.', 'administrator_add_error': 'Toevoegen mislukt. Het e-mailadres bestaat mogelijk al.',
      'delete_local_account': 'Mijn lokale account verwijderen', 'delete': 'Verwijderen', 'delete_post': 'Bericht verwijderen', 'delete_post_confirm': 'Dit bericht verwijderen?', 'reaction': 'Reactie',
      'delete_account_warning': 'Het huidige lokale account wordt verwijderd en u kunt een ander aanmaken. Deze actie kan niet ongedaan worden gemaakt.',
      'password_privacy_note': 'Om veiligheidsredenen wordt het wachtwoord niet automatisch opgeslagen. Het e-mailadres kan wel worden onthouden.',
      'support_us': 'Steun ons', 'support_title': 'Steun de ontwikkeling',
      'support_message': 'Onthoud dat het onderhoud van de app kosten met zich meebrengt. Als u wilt, kunt u ons steunen met een donatie naar keuze om de ontwikkeling en verbetering van de app te helpen. Hartelijk dank!',
      'blick_number': 'Blick-nummer', 'close': 'Sluiten', 'number_copied': 'Nummer gekopieerd',
      'pending_users_notice': 'Er zijn accounts die goedkeuring nodig hebben',
      'no_account_found': 'Er bestaat geen account met dit e-mailadres.', 'password_mismatch': 'Het wachtwoord komt niet overeen.',
      'account_pending_approval': 'Het account wacht op goedkeuring door een beheerder.', 'login_failed_generic': 'Inloggen is mislukt.',
      'reset_link_sent': 'We hebben een link om uw wachtwoord opnieuw in te stellen naar uw e-mail gestuurd.',
      'reset_link_instructions': 'Vul uw e-mail in en we sturen u een link om een nieuw wachtwoord in te stellen.',
      'feed': 'Prikbord', 'feed_subtitle': 'Foto’s en momenten van de stal', 'new_post': 'Nieuw bericht', 'post_caption_hint': 'Schrijf iets...',
      'add_photo': 'Foto toevoegen', 'add_photo_video': 'Foto of video toevoegen', 'play_video': 'Video afspelen', 'publish': 'Plaatsen', 'no_posts': 'Nog geen berichten. Wees de eerste!', 'comment': 'Reageren',
      'post_error': 'Plaatsen mislukt:',
      'stable_facebook': 'Facebook van de stal',
      'transfer_primary_title': 'Hoofdbeheerder wijzigen', 'transfer_primary_action': 'Tot hoofdbeheerder maken',
      'transfer_primary_confirm_prefix': 'Wilt u', 'transfer_primary_confirm_suffix': 'tot hoofdbeheerder maken? U verliest deze rol.',
      'transfer_primary_success': 'De rol van hoofdbeheerder is overgedragen.', 'transfer_primary_error': 'De rol kon niet worden overgedragen.',
      'owner_panel_title': 'Onderhoudspaneel',
    },
    'fr': {
      'dashboard': 'Panneau d’administration', 'notifications': 'Notifications', 'notifications_empty': 'Aucune nouvelle notification.', 'work_area': 'Espace de travail',
      'choose_module': 'Sélectionnez un module pour commencer.', 'horses': 'Chevaux', 'your_friends': 'Vos amis',
      'horse_subtitle': 'Fiches et santé', 'monitoring': 'Surveillance',
      'monitoring_subtitle': 'Données en temps réel', 'records': 'Registres',
      'records_subtitle': 'Historique et événements', 'users': 'Utilisateurs', 'admin_role': 'Administrateur',
      'users_subtitle': 'Gérer les accès', 'veterinarian': 'Vétérinaire',
      'veterinarian_subtitle': 'Données et évaluations', 'settings': 'Paramètres',
      'language': 'Langue de l’application', 'save': 'Enregistrer', 'add': 'Ajouter',
      'logout': 'Se déconnecter', 'in_development': 'Module en construction',
      'horse_card': 'Fiche du cheval', 'veterinarian_card': 'Fiche du vétérinaire',
      'owner_card': 'Fiche du propriétaire', 'address': 'Adresse', 'current_address': 'Adresse actuelle',
      'national_id': 'PESEL / pièce d’identité', 'horse_id': 'Numéro d’identification du cheval',
      'private_data_notice': 'Donnée privée. Visible après déverrouillage.', 'show_data': 'Afficher', 'hide_data': 'Masquer',
      'pathologies': 'Pathologies et maladies', 'horses_owned': 'Chevaux possédés', 'license_number': 'Numéro de licence vétérinaire', 'clinic_address': 'Adresse de la clinique ou du cabinet',
      'name': 'Nom complet', 'email': 'E-mail', 'phone': 'Téléphone',
      'clinic': 'Clinique', 'breed': 'Race', 'birth_date': 'Date de naissance', 'birth_date_required': 'Touchez pour choisir votre date de naissance', 'age_restriction': 'L’inscription est réservée aux personnes de 18 ans ou plus.',
      'microchip': 'Numéro de puce', 'notes': 'Observations', 'saved': 'Informations enregistrées',
      'connected_sensor': 'Capteur connecté', 'live': 'En direct', 'temperature': 'Température',
      'humidity': 'Humidité', 'ammonia': 'Ammoniac', 'air_quality': 'Qualité de l’air',
      'sensor_notice': 'Données de démonstration avant la connexion de l’ESP32.', 'add_record': 'Ajouter un enregistrement',
      'record_title': 'Titre', 'details': 'Détails', 'cancel': 'Annuler', 'no_records': 'Aucun enregistrement sauvegardé',
      'care_plan': 'Plan de traitement', 'add_medication': 'Ajouter un médicament', 'medication': 'Médicament',
      'dose': 'Dose', 'next_date': 'Prochaine date', 'no_medication': 'Aucun médicament planifié',
      'frequency': 'Fréquence', 'daily': 'Quotidien', 'weekly': 'Hebdomadaire', 'once': 'Une fois',
      'owner': 'Propriétaire', 'owner_subtitle': 'Coordonnées', 'care_subtitle': 'Médicaments et dates',
      'report': 'Rapport PDF', 'report_subtitle': 'Exporter l’historique', 'generate_report': 'Générer le rapport',
      'user_management': 'Gestion des utilisateurs', 'user_management_subtitle': 'Valider les comptes',
      'welcome': 'Bienvenue',
      'cctv': 'Caméras CCTV', 'cctv_subtitle': 'Sécurité de l’écurie',
      'chat': 'Chat', 'chat_subtitle': 'Espace communautaire', 'private_message': 'Privé', 'message_deleted': 'Message supprimé.',
      'welcome_message': 'Bienvenue sur Equi_Harmony_Monitor', 'login': 'Se connecter',
      'create_account': 'Créer un compte', 'forgot_password': 'Mot de passe oublié',
      'admin_access': 'Accès administrateur', 'show_password': 'Afficher le mot de passe', 'hide_password': 'Masquer le mot de passe',
      'password': 'Mot de passe', 'admin_only_access': 'Accès réservé aux administrateurs',
      'admin_email': 'E-mail administrateur', 'checking': 'Vérification...', 'enter_as_admin': 'Entrer en tant qu’administrateur',
      'invalid_admin_credentials': 'E-mail, mot de passe ou rôle administrateur incorrect.',
      'select_roles': 'Sélectionnez un ou plusieurs rôles :', 'role_admin': 'Administrateur', 'role_owner': 'Propriétaire de chevaux', 'role_veterinarian': 'Vétérinaire',
      'fill_required_fields': 'Renseignez le nom, l’e-mail, un mot de passe de 6 caractères et au moins un rôle.',
      'stable_name_optional': 'Nom de l’écurie (facultatif)', 'min_password_chars': 'Minimum 6 caractères',
      'account_exists_title': 'Compte existant', 'account_exists_message': 'Un compte existe déjà avec cet e-mail. Utilisez un autre e-mail ou connectez-vous.',
      'account_created_title': 'Compte créé', 'account_created_message': 'Votre compte administrateur a été créé avec succès.',
      'request_sent_title': 'Demande envoyée', 'request_sent_message': 'Le compte a été enregistré avec succès et est en attente d’approbation.',
      'register_pending_notice': 'Indiquez seulement votre nom, e-mail et mot de passe. Le rôle et l’approbation seront définis par l’administrateur/assistant.',
      'select_roles_required': 'Sélectionnez au moins un rôle avant d’approuver.',
      'account_error_title': 'Impossible de créer le compte', 'account_error_message_prefix': 'Une erreur s’est produite lors de l’enregistrement :',
      'accept': 'Accepter', 'saving': 'Enregistrement...', 'submit_request': 'Envoyer la demande',
      'reset_password': 'Réinitialiser le mot de passe', 'new_password': 'Nouveau mot de passe', 'password_updated': 'Mot de passe mis à jour. Vous pouvez maintenant vous connecter.',
      'email_not_found': 'E-mail introuvable ou mot de passe trop court.',
      'add_camera': 'Ajouter une caméra', 'add_camera_title': 'Ajouter une caméra CCTV', 'camera_name': 'Nom de la caméra', 'camera_url': 'URL/IP ou RTSP',
      'camera_open_error': 'Impossible d’ouvrir la caméra. Vérifiez l’URL, le réseau Wi-Fi et le protocole.',
      'no_cameras': 'Ajoutez une caméra Wi-Fi via URL/IP ou RTSP.',
      'chat_access_required': 'L’administrateur doit vous donner accès au chat.', 'chat_community': 'Chat de la communauté',
      'play_voice_message': 'Lire le message vocal', 'send_message_error': 'Impossible d’envoyer le message :',
      'video_label': 'Vidéo', 'photo_label': 'Photo',
      'photo_or_video': 'Photo ou vidéo', 'stop_recording': 'Arrêter l’enregistrement', 'record_voice': 'Enregistrer la voix',
      'write_message_hint': 'Écrivez un message ou un emoji', 'send': 'Envoyer',
      'validate_users': 'Validation des utilisateurs', 'add_administrator': 'Ajouter un administrateur', 'no_users': 'Aucun utilisateur enregistré.',
      'chat_room_access': 'Accès à la salle de chat', 'reject': 'Rejeter', 'approve': 'Approuver', 'delete_account': 'Supprimer le compte',
      'delete_account_confirm_prefix': 'Voulez-vous supprimer le compte de', 'delete_account_confirm_suffix': '? Cette action est irréversible.',
      'account_deleted': 'Compte supprimé.', 'account_delete_error': 'Impossible de supprimer ce compte.',
      'stable_label': 'Écurie', 'status_label': 'Statut', 'roles_label': 'Rôles',
      'administrator_added': 'Administrateur ajouté.', 'administrator_add_error': 'Impossible d’ajouter. L’e-mail existe peut-être déjà.',
      'delete_local_account': 'Supprimer mon compte local', 'delete': 'Supprimer', 'delete_post': 'Supprimer la publication', 'delete_post_confirm': 'Supprimer cette publication ?', 'reaction': 'Réaction',
      'delete_account_warning': 'Le compte local actuel sera supprimé et vous pourrez en créer un autre. Cette action est irréversible.',
      'password_privacy_note': 'Pour des raisons de sécurité, le mot de passe n’est pas enregistré automatiquement. L’e-mail peut l’être.',
      'support_us': 'Soutenez-nous', 'support_title': 'Soutenez le développement',
      'support_message': 'N’oubliez pas que la maintenance de l’application a un coût. Si vous le souhaitez, vous pouvez nous soutenir avec le don de votre choix pour aider au développement et à l’amélioration de l’application. Merci beaucoup !',
      'blick_number': 'Numéro Blick', 'close': 'Fermer', 'number_copied': 'Numéro copié',
      'pending_users_notice': 'Des comptes sont en attente d’approbation',
      'no_account_found': 'Aucun compte n’existe avec cet e-mail.', 'password_mismatch': 'Le mot de passe ne correspond pas.',
      'account_pending_approval': 'Le compte est en attente d’approbation par un administrateur.', 'login_failed_generic': 'Connexion impossible.',
      'reset_link_sent': 'Nous vous avons envoyé un lien pour réinitialiser votre mot de passe par e-mail.',
      'reset_link_instructions': 'Saisissez votre e-mail et nous vous enverrons un lien pour créer un nouveau mot de passe.',
      'feed': 'Fil d’actualité', 'feed_subtitle': 'Photos et moments de l’écurie', 'new_post': 'Nouvelle publication', 'post_caption_hint': 'Écrivez quelque chose...',
      'add_photo': 'Ajouter une photo', 'add_photo_video': 'Ajouter une photo ou une vidéo', 'play_video': 'Lire la vidéo', 'publish': 'Publier', 'no_posts': 'Pas encore de publications. Soyez le premier !', 'comment': 'Commenter',
      'post_error': 'Impossible de publier :',
      'stable_facebook': 'Facebook de l’écurie',
      'transfer_primary_title': 'Changer l’administrateur principal', 'transfer_primary_action': 'Définir comme administrateur principal',
      'transfer_primary_confirm_prefix': 'Voulez-vous faire de', 'transfer_primary_confirm_suffix': 'l’administrateur principal ? Vous perdrez ce rôle.',
      'transfer_primary_success': 'Le rôle d’administrateur principal a été transféré.', 'transfer_primary_error': 'Impossible de transférer le rôle.',
      'owner_panel_title': 'Panneau de maintenance',
    },
    'en': {
      'dashboard': 'Administration panel', 'notifications': 'Notifications', 'notifications_empty': 'No new notifications.', 'work_area': 'Workspace',
      'choose_module': 'Select a module to begin.', 'horses': 'Horses', 'your_friends': 'Your friends',
      'horse_subtitle': 'Profiles and health status', 'monitoring': 'Monitoring',
      'monitoring_subtitle': 'Real-time data', 'records': 'Records',
      'records_subtitle': 'History and events', 'users': 'Users', 'admin_role': 'Administrator',
      'users_subtitle': 'Manage access', 'veterinarian': 'Veterinarian',
      'veterinarian_subtitle': 'Details and evaluations', 'settings': 'Settings',
      'language': 'Application language', 'save': 'Save', 'add': 'Add',
      'logout': 'Log out', 'in_development': 'Module under construction',
      'horse_card': 'Horse profile', 'veterinarian_card': 'Veterinarian profile',
      'owner_card': 'Owner profile', 'address': 'Address', 'current_address': 'Current address',
      'national_id': 'PESEL / ID card', 'horse_id': 'Horse identification number',
      'private_data_notice': 'Private data. Visible only when unlocked.', 'show_data': 'Show', 'hide_data': 'Hide',
      'pathologies': 'Pathologies and diseases', 'horses_owned': 'Owned horses', 'license_number': 'Veterinary license number', 'clinic_address': 'Clinic or practice address',
      'name': 'Full name', 'email': 'Email address', 'phone': 'Phone',
      'clinic': 'Clinic', 'breed': 'Breed', 'birth_date': 'Birth date', 'birth_date_required': 'Tap to select your birth date', 'age_restriction': 'Registration is limited to people aged 18 or older.',
      'microchip': 'Microchip number', 'notes': 'Notes', 'saved': 'Information saved',
      'connected_sensor': 'Connected sensor', 'live': 'Live', 'temperature': 'Temperature',
      'humidity': 'Humidity', 'ammonia': 'Ammonia', 'air_quality': 'Air quality',
      'sensor_notice': 'Demo data until the ESP32 is connected.', 'add_record': 'Add record',
      'record_title': 'Record title', 'details': 'Details', 'cancel': 'Cancel', 'no_records': 'No saved records',
      'care_plan': 'Care plan', 'add_medication': 'Add medication', 'medication': 'Medication',
      'dose': 'Dose', 'next_date': 'Next date', 'no_medication': 'No medication scheduled',
      'frequency': 'Frequency', 'daily': 'Daily', 'weekly': 'Weekly', 'once': 'Once',
      'owner': 'Owner', 'owner_subtitle': 'Contact details', 'care_subtitle': 'Medication and dates',
      'report': 'PDF report', 'report_subtitle': 'Export history', 'generate_report': 'Generate report',
      'user_management': 'User management', 'user_management_subtitle': 'Validate accounts',
      'welcome': 'Welcome',
      'cctv': 'CCTV cameras', 'cctv_subtitle': 'Stable security',
      'chat': 'Chat', 'chat_subtitle': 'Community room', 'private_message': 'Private', 'message_deleted': 'Message deleted.',
      'welcome_message': 'Welcome to Equi_Harmony_Monitor', 'login': 'Log in',
      'create_account': 'Create account', 'forgot_password': 'Forgot password',
      'admin_access': 'Administrator access', 'show_password': 'Show password', 'hide_password': 'Hide password',
      'password': 'Password', 'admin_only_access': 'Access restricted to administrators',
      'admin_email': 'Administrator email', 'checking': 'Checking...', 'enter_as_admin': 'Enter as administrator',
      'invalid_admin_credentials': 'Incorrect email, password, or administrator role.',
      'select_roles': 'Select one or more roles:', 'role_admin': 'Administrator', 'role_owner': 'Horse owner', 'role_veterinarian': 'Veterinarian',
      'fill_required_fields': 'Fill in name, email, a 6-character password, and at least one role.',
      'stable_name_optional': 'Stable name (optional)', 'min_password_chars': 'Minimum 6 characters',
      'account_exists_title': 'Existing account', 'account_exists_message': 'An account already exists with that email. Use another email or log in.',
      'account_created_title': 'Account created', 'account_created_message': 'Your administrator account was created successfully.',
      'request_sent_title': 'Request sent', 'request_sent_message': 'The account was saved successfully and is pending approval.',
      'register_pending_notice': 'Just enter your name, email and password. The admin/assistant will set the role and approve your account.',
      'select_roles_required': 'Select at least one role before approving.',
      'account_error_title': 'Could not create account', 'account_error_message_prefix': 'An error occurred while saving:',
      'accept': 'Accept', 'saving': 'Saving...', 'submit_request': 'Submit request',
      'reset_password': 'Reset password', 'new_password': 'New password', 'password_updated': 'Password updated. You can now log in.',
      'email_not_found': 'Email not found or password too short.',
      'add_camera': 'Add camera', 'add_camera_title': 'Add CCTV camera', 'camera_name': 'Camera name', 'camera_url': 'URL/IP or RTSP',
      'camera_open_error': 'Could not open the camera. Check the URL, Wi-Fi network, and protocol.',
      'no_cameras': 'Add a Wi-Fi camera via URL/IP or RTSP.',
      'chat_access_required': 'The administrator must grant you access to the chat.', 'chat_community': 'Community chat',
      'play_voice_message': 'Play voice message', 'send_message_error': 'Could not send the message:',
      'video_label': 'Video', 'photo_label': 'Photo',
      'photo_or_video': 'Photo or video', 'stop_recording': 'Stop recording', 'record_voice': 'Record voice',
      'write_message_hint': 'Write a message or emoji', 'send': 'Send',
      'validate_users': 'User validation', 'add_administrator': 'Add administrator', 'no_users': 'No registered users.',
      'chat_room_access': 'Chat room access', 'reject': 'Reject', 'approve': 'Approve', 'delete_account': 'Delete account',
      'delete_account_confirm_prefix': 'Do you want to delete the account of', 'delete_account_confirm_suffix': '? This action cannot be undone.',
      'account_deleted': 'Account deleted.', 'account_delete_error': 'This account cannot be deleted.',
      'stable_label': 'Stable', 'status_label': 'Status', 'roles_label': 'Roles',
      'administrator_added': 'Administrator added.', 'administrator_add_error': 'Could not add. The email may already exist.',
      'delete_local_account': 'Delete my local account', 'delete': 'Delete', 'delete_post': 'Delete post', 'delete_post_confirm': 'Delete this post?', 'reaction': 'Reaction',
      'delete_account_warning': 'The current local account will be deleted and you can create another one. This action cannot be undone.',
      'password_privacy_note': 'For security, the password is not saved automatically. The email can be remembered.',
      'support_us': 'Support us', 'support_title': 'Support the development',
      'support_message': 'Please remember that maintaining the app has a cost. If you’d like, you can support us with any donation you wish to help with the development and improvement of the app. Thank you very much!',
      'blick_number': 'Blick number', 'close': 'Close', 'number_copied': 'Number copied',
      'pending_users_notice': 'You have accounts pending approval',
      'no_account_found': 'No account exists with that email.', 'password_mismatch': 'The password does not match.',
      'account_pending_approval': 'The account is pending approval by an administrator.', 'login_failed_generic': 'Could not log in.',
      'reset_link_sent': 'We sent a password reset link to your email.',
      'reset_link_instructions': 'Enter your email and we will send you a link to set a new password.',
      'feed': 'Feed', 'feed_subtitle': 'Photos and moments from the stable', 'new_post': 'New post', 'post_caption_hint': 'Write something...',
      'add_photo': 'Add photo', 'add_photo_video': 'Add photo or video', 'play_video': 'Play video', 'publish': 'Publish', 'no_posts': 'No posts yet. Be the first!', 'comment': 'Comment',
      'post_error': 'Could not publish:',
      'stable_facebook': 'Stable Facebook page',
      'transfer_primary_title': 'Change primary administrator', 'transfer_primary_action': 'Make primary administrator',
      'transfer_primary_confirm_prefix': 'Do you want to make', 'transfer_primary_confirm_suffix': 'the primary administrator? You will lose this role.',
      'transfer_primary_success': 'The primary administrator role was transferred.', 'transfer_primary_error': 'Could not transfer the role.',
      'owner_panel_title': 'Maintenance panel',
    },
    'pt': {
      'dashboard': 'Painel de administração', 'notifications': 'Notificações', 'notifications_empty': 'Não há novas notificações.', 'work_area': 'Área de trabalho',
      'choose_module': 'Selecione um módulo para começar.', 'horses': 'Cavalos', 'your_friends': 'Os seus amigos',
      'horse_subtitle': 'Fichas e saúde', 'monitoring': 'Monitoramento',
      'monitoring_subtitle': 'Dados em tempo real', 'records': 'Registros',
      'records_subtitle': 'Histórico e eventos', 'users': 'Usuários', 'admin_role': 'Administrador',
      'users_subtitle': 'Gerenciar acessos', 'veterinarian': 'Veterinário',
      'veterinarian_subtitle': 'Dados e avaliações', 'settings': 'Configurações',
      'language': 'Idioma do aplicativo', 'save': 'Salvar', 'add': 'Adicionar',
      'logout': 'Sair', 'in_development': 'Módulo em construção',
      'horse_card': 'Ficha do cavalo', 'veterinarian_card': 'Ficha do veterinário',
      'owner_card': 'Ficha do proprietário', 'address': 'Endereço', 'current_address': 'Endereço atual',
      'national_id': 'PESEL / documento de identidade', 'horse_id': 'Número de identificação do cavalo',
      'private_data_notice': 'Dado privado. Visível somente após desbloqueio.', 'show_data': 'Mostrar', 'hide_data': 'Ocultar',
      'pathologies': 'Patologias e doenças', 'horses_owned': 'Cavalos próprios', 'license_number': 'Número da licença veterinária', 'clinic_address': 'Endereço da clínica ou consultório',
      'name': 'Nome completo', 'email': 'E-mail', 'phone': 'Telefone',
      'clinic': 'Clínica', 'breed': 'Raça', 'birth_date': 'Data de nascimento', 'birth_date_required': 'Toque para selecionar a sua data de nascimento', 'age_restriction': 'O registo é permitido apenas a pessoas com 18 anos ou mais.',
      'microchip': 'Número do microchip', 'notes': 'Observações', 'saved': 'Informações salvas',
      'connected_sensor': 'Sensor conectado', 'live': 'Ao vivo', 'temperature': 'Temperatura',
      'humidity': 'Umidade', 'ammonia': 'Amônia', 'air_quality': 'Qualidade do ar',
      'sensor_notice': 'Dados de demonstração até conectar o ESP32.', 'add_record': 'Adicionar registro',
      'record_title': 'Título do registro', 'details': 'Detalhes', 'cancel': 'Cancelar', 'no_records': 'Nenhum registro salvo',
      'care_plan': 'Plano de tratamento', 'add_medication': 'Adicionar medicamento', 'medication': 'Medicamento',
      'dose': 'Dose', 'next_date': 'Próxima data', 'no_medication': 'Nenhum medicamento agendado',
      'frequency': 'Frequência', 'daily': 'Diária', 'weekly': 'Semanal', 'once': 'Uma vez',
      'owner': 'Proprietário', 'owner_subtitle': 'Dados de contato', 'care_subtitle': 'Medicamentos e datas',
      'report': 'Relatório PDF', 'report_subtitle': 'Exportar histórico', 'generate_report': 'Gerar relatório',
      'user_management': 'Gestão de usuários', 'user_management_subtitle': 'Validar contas',
      'welcome': 'Bem-vindo',
      'cctv': 'Câmeras CCTV', 'cctv_subtitle': 'Segurança do estábulo',
      'chat': 'Chat', 'chat_subtitle': 'Sala da comunidade', 'private_message': 'Privado', 'message_deleted': 'Mensagem eliminada.',
      'welcome_message': 'Bem-vindo ao Equi_Harmony_Monitor', 'login': 'Entrar',
      'create_account': 'Criar conta', 'forgot_password': 'Esqueci minha senha',
      'admin_access': 'Acesso administrador', 'show_password': 'Mostrar senha', 'hide_password': 'Ocultar senha',
      'password': 'Senha', 'admin_only_access': 'Acesso exclusivo para administradores',
      'admin_email': 'E-mail do administrador', 'checking': 'Verificando...', 'enter_as_admin': 'Entrar como administrador',
      'invalid_admin_credentials': 'E-mail, senha ou função de administrador incorretos.',
      'select_roles': 'Selecione uma ou mais funções:', 'role_admin': 'Administrador', 'role_owner': 'Proprietário de cavalos', 'role_veterinarian': 'Veterinário',
      'fill_required_fields': 'Preencha nome, e-mail, senha de 6 caracteres e pelo menos uma função.',
      'stable_name_optional': 'Nome do estábulo (opcional)', 'min_password_chars': 'Mínimo de 6 caracteres',
      'account_exists_title': 'Conta existente', 'account_exists_message': 'Já existe uma conta com esse e-mail. Use outro e-mail ou faça login.',
      'account_created_title': 'Conta criada', 'account_created_message': 'Sua conta de administrador foi criada com sucesso.',
      'request_sent_title': 'Solicitação enviada', 'request_sent_message': 'A conta foi salva com sucesso e está pendente de aprovação.',
      'register_pending_notice': 'Indique apenas nome, e-mail e senha. A função e a aprovação serão definidas pelo administrador/assistente.',
      'select_roles_required': 'Selecione pelo menos uma função antes de aprovar.',
      'account_error_title': 'Não foi possível criar a conta', 'account_error_message_prefix': 'Ocorreu um erro ao salvar:',
      'accept': 'Aceitar', 'saving': 'Salvando...', 'submit_request': 'Enviar solicitação',
      'reset_password': 'Redefinir senha', 'new_password': 'Nova senha', 'password_updated': 'Senha atualizada. Você já pode fazer login.',
      'email_not_found': 'E-mail não encontrado ou senha muito curta.',
      'add_camera': 'Adicionar câmera', 'add_camera_title': 'Adicionar câmera CCTV', 'camera_name': 'Nome da câmera', 'camera_url': 'URL/IP ou RTSP',
      'camera_open_error': 'Não foi possível abrir a câmera. Verifique a URL, a rede Wi-Fi e o protocolo.',
      'no_cameras': 'Adicione uma câmera Wi-Fi via URL/IP ou RTSP.',
      'chat_access_required': 'O administrador precisa lhe conceder acesso ao chat.', 'chat_community': 'Chat da comunidade',
      'play_voice_message': 'Reproduzir mensagem de voz', 'send_message_error': 'Não foi possível enviar a mensagem:',
      'video_label': 'Vídeo', 'photo_label': 'Foto',
      'photo_or_video': 'Foto ou vídeo', 'stop_recording': 'Parar gravação', 'record_voice': 'Gravar voz',
      'write_message_hint': 'Escreva uma mensagem ou emoji', 'send': 'Enviar',
      'validate_users': 'Validação de usuários', 'add_administrator': 'Adicionar administrador', 'no_users': 'Nenhum usuário registrado.',
      'chat_room_access': 'Acesso à sala de chat', 'reject': 'Rejeitar', 'approve': 'Aprovar', 'delete_account': 'Excluir conta',
      'delete_account_confirm_prefix': 'Deseja excluir a conta de', 'delete_account_confirm_suffix': '? Esta ação não pode ser desfeita.',
      'account_deleted': 'Conta excluída.', 'account_delete_error': 'Não é possível excluir esta conta.',
      'stable_label': 'Estábulo', 'status_label': 'Status', 'roles_label': 'Funções',
      'administrator_added': 'Administrador adicionado.', 'administrator_add_error': 'Não foi possível adicionar. O e-mail pode já existir.',
      'delete_local_account': 'Excluir minha conta local', 'delete': 'Excluir', 'delete_post': 'Excluir publicação', 'delete_post_confirm': 'Excluir esta publicação?', 'reaction': 'Reação',
      'delete_account_warning': 'A conta local atual será apagada e você poderá criar outra. Esta ação não pode ser desfeita.',
      'password_privacy_note': 'Por segurança, a senha não é salva automaticamente. O e-mail pode ser lembrado.',
      'support_us': 'Apoie-nos', 'support_title': 'Apoie o desenvolvimento',
      'support_message': 'Por favor, lembre-se de que a manutenção do aplicativo tem um custo. Se desejar, você pode nos apoiar com a doação que quiser para ajudar no desenvolvimento e melhoria do aplicativo. Agradecemos muito!',
      'blick_number': 'Número Blick', 'close': 'Fechar', 'number_copied': 'Número copiado',
      'pending_users_notice': 'Há contas pendentes de aprovação',
      'no_account_found': 'Não existe uma conta com esse e-mail.', 'password_mismatch': 'A senha não corresponde.',
      'account_pending_approval': 'A conta está pendente de aprovação por um administrador.', 'login_failed_generic': 'Não foi possível fazer login.',
      'reset_link_sent': 'Enviamos um link para redefinir sua senha para o seu e-mail.',
      'reset_link_instructions': 'Digite seu e-mail e enviaremos um link para criar uma nova senha.',
      'feed': 'Mural', 'feed_subtitle': 'Fotos e momentos do estábulo', 'new_post': 'Nova publicação', 'post_caption_hint': 'Escreva algo...',
      'add_photo': 'Adicionar foto', 'add_photo_video': 'Adicionar foto ou vídeo', 'play_video': 'Reproduzir vídeo', 'publish': 'Publicar', 'no_posts': 'Ainda não há publicações. Seja o primeiro!', 'comment': 'Comentar',
      'post_error': 'Não foi possível publicar:',
      'stable_facebook': 'Facebook do estábulo',
      'transfer_primary_title': 'Alterar administrador principal', 'transfer_primary_action': 'Tornar administrador principal',
      'transfer_primary_confirm_prefix': 'Deseja tornar', 'transfer_primary_confirm_suffix': 'o administrador principal? Você perderá essa função.',
      'transfer_primary_success': 'A função de administrador principal foi transferida.', 'transfer_primary_error': 'Não foi possível transferir a função.',
      'owner_panel_title': 'Painel de manutenção',
    },
  };

  static String get(AppLanguage language, String key) =>
      _values[language.name]?[key] ?? _values['pl']![key] ?? key;
}
